### ISSUE TITLE
Can this network be used to extract table from a document? 

### ISSUE THREAD

**Issue by jewelc92** [dhlab-epfl/dhSegment#13]
Can this network be used to extract table from a document?  If it could be, how to do it? Painting the table lines in red and the others in black?

**Comment by solivr** [comment]
Depending on what you want you have two options:
* You can annotate the graphical lines of the table: this would mean having a black image with only the table graphical lines in red (or another color you'd like). This way the network will extract the table graphical lines.
* You can annotate the entire table by an enclosing box; this means the network will be able to locate and extract the entire table region. The annotated image would consist of a black image with a (red) box representing the table object.

If you want the content of the table, then you can try to annotate only the text lines inside the table (not sure this would work though), or combine a table extractor (i.e the second option above) with a text line extractor.
