### ISSUE TITLE
Demo for Document layout analysis

### ISSUE THREAD

**Issue by harirajeev** [dhlab-epfl/dhSegment#30]
Could you please help with including "document layout analysis" in demo ?.
Thanks for your help.

**Comment by solivr** [comment]
Hello,
The demo serves the purpose of checking that you're installation is properly done and to get an example of how a training / prediction with dhSegment could be run, but we do not plan to extend it for the moment.
By the way, what do you mean by "document layout analysis", what do you want to extract ?

**Comment by harirajeev** [comment]
thank you.
