### ISSUE TITLE
ICDAR 2019 Competition on Baseline Detection (cBAD)?

### ISSUE THREAD

**Issue by mrocr** [dhlab-epfl/dhSegment#31]
@solivr @SeguinBe Will you participate in the ICDAR 2019 cBAD competition?
Do you have any plans to optimize dhSegment?

**Comment by solivr** [comment]
Hi, personally I do not plan to take part in ICDAR competitions.
What kind of optimizations are you thinking of ?

**Comment by mrocr** [comment]
Non in particular, just was asking to see if you were interested in the [Baseline Detection](https://zenodo.org/record/2567398) competition.

Anyways, dhSegment is already achieving high detection rates, you have done a great job.
