### ISSUE TITLE
how to use baseline post process

### ISSUE THREAD

**Issue by lius0-0** [dhlab-epfl/dhSegment#33]
About find baseline.i get the line mask,but I don't know how to extract line,I try to change the demo.py.Could you show me about baseline demo?thank you.

**Comment by solivr** [comment]
Hi,
You can have a look at [this tutorial ](https://github.com/dhlab-epfl/FDH_Tutorial_ComputerVision_DeepLearning/blob/master/3-CV_applications/Historical%20document%20processing/Page%20extraction%20%2B%20Textline%20detection.ipynb) which should give you an insight on the main steps.
Feel free to ask if it's still not clear.
