### ISSUE TITLE
detecting multiple instances of same object

### ISSUE THREAD

**Issue by ankur7721** [dhlab-epfl/dhSegment#41]
Like the way [this ](https://dhlab-epfl.github.io/dhSegment/#ornament-extraction) page shows multiple ornament extraction on same page, My model never detects more than one instance of a similar object.

I am using the same `demo.py` as in master branch.

Can someone help me ?

**Comment by solivr** [comment]
Hello @ankur7721 ,
If you're reusing the `demo.py` make sure you update the parameters of the `find_boxes` function. For example, on [this line](https://github.com/dhlab-epfl/dhSegment/blob/b5cbbc6448139bf37f05a2c1effd5a6edc6901f3/demo.py#L84) you need to update `n_max_boxes=np.inf`. I recommend also having a look at the documentation for the other parameters.

**Comment by ankur7721** [comment]
hi @solivr 
Thanks for your reply. I have already conigured `n_max_boxes` on that line.

Is there any other thing I could have missed ?

**Comment by solivr** [comment]
What about `min_area` parameter ? ([doc](https://dhsegment.readthedocs.io/en/latest/reference/post_processing.html#dh_segment.post_processing.find_boxes)). If the objects you are trying to detect are small, they may be filtered out by the default value. Try setting it to `min_area=0.0`.

**Comment by ankur7721** [comment]
Thanks a lot @solivr . It works by changing `min_area` :)
