### ISSUE TITLE
pages_sample.zip link not working

### ISSUE THREAD

**Issue by gpetz** [dhlab-epfl/dhSegment#45]
Really like the idea of using Jupyter Notebooks introduced in https://github.com/dhlab-epfl/dhSegment/commit/9889c7dd58333538980158afa844439e338ee8e0. Nevertheless the link for pages-sample.zip (https://github.com/dhlab-epfl/dhSegment/releases/download/untagged-b55f9aa4fff5efd4b1b8/pages_sample.zip) isn't working.

**Comment by solivr** [comment]
Thanks for reporting it, it should be corrected now.
