### ISSUE TITLE
Which CUDA, cudnn and tensorflow versions are meant to be used together

### ISSUE THREAD

**Issue by kamilspiewak** [dhlab-epfl/dhSegment#54]
I am doing some small project for multilabel classification, but during training I'm keep getting errors about 
![image](https://user-images.githubusercontent.com/43140786/72014877-05dff000-3261-11ea-8102-115aba5bb093.png)

![image](https://user-images.githubusercontent.com/43140786/72014899-109a8500-3261-11ea-8870-effa70ea7bfe.png)
Tests were made with TensorflowGPU 1.13.1, CUDA 10.1 and cudnn 7.6.5.32 under Windows 10 

Is this related to my bad configuration of project, incorrect installation of CUDA and cudnn or versions missmatch between those three?

**Comment by solivr** [comment]
Yes it is most probably due to versions missmatch between tensorflow, cuda and cudnn.
On Ubuntu 18.04, I have tensorflow 1.13, cuda 9.0 and cudnn 7.6.3.
Maybe try to have a look at tensorfow issues related to this error message.

**Comment by Gawajn** [comment]
you can check [https://www.tensorflow.org/install/source_windows#gpu](https://www.tensorflow.org/install/source_windows#gpu) (Linux: [https://www.tensorflow.org/install/source#gpu](https://www.tensorflow.org/install/source#gpu)) for compatible cuda/cudnn/tensorflow versions
