### ISSUE TITLE
Layout Analysis Use Case: DIVA-HisDB

### ISSUE THREAD

**Issue by doobybug** [dhlab-epfl/dhSegment#56]
Hi,

Are there any plans to issue the training and demo for layout analysis on DIVA-HisDB?

**Comment by solivr** [comment]
Hello,

No there are no plans to do a special example for the DIVA-HisDB dataset. It should be quite similar to the cBAD and the Page demo. If you're experimenting particular problems to have the training running, feel free to ask.
With a bit of archeology you can also see what we had implemented [here](https://github.com/dhlab-epfl/dhSegment/tree/v0.4.0/exps/diva).

**Comment by doobybug** [comment]
Hi. thank you so much for answering me. I will definitely look into it. I would like to experiment with your code to classify text and handwritten text in the same document and maybe get their boundary boxes. Which route do you think I should take it? Page segmentation or Layout analysis?

**Comment by solivr** [comment]
Your task looks more similar to the DIVA-HisDB task than to the page segmentation task. So I would go more into the direction of document image analysis.
If you need a guide for the principal steps you can have also a look at [this notebook](https://github.com/solivr/workshop_dhd19/blob/master/wk_dhd.ipynb). However I would recommend in you case to try to annotate the text at pixel level as it is done for the DIVA-HisDB experiment (and not with bounding boxes around text).
