### ISSUE TITLE
Read Tag Values from XML file

### ISSUE THREAD

**Issue by sanakhamekhem** [dhlab-epfl/dhSegment#57]
Dear Sir,

I would like to get coordinates of text lines of a document from xml file.
I'm using the function:
tl_coords=PAGE.get_unique_tags_from_xml_text_regions(xml_filename= str, tag_pattern= 'type:Page/TextRegion/TextLine/Coords points')

But, the output is null. I'm asking if you can specify how the tag pattern should be in input.
Thank you in advance.

**Comment by solivr** [comment]
Hello,

With the function `PAGE.get_unique_tags_from_xml_text_regions` you should have a `custom` filed in your xml object.
Then you can pass any pattern you'd like to the `tag_pattern` parameter (`'{type:.*;}'` by default).

For instance if your xml object looks like this:   
`<TextRegion id="0001" custom="structure {type:point;}">`    
calling `PAGE.get_unique_tags_from_xml_text_regions(xml_filename=filename)` should return `['point']`.
