### ISSUE TITLE
Baselines to Textlines

### ISSUE THREAD

**Issue by ghost** [dhlab-epfl/dhSegment#58]
@solivr @SeguinBe @raphaelBarman 

Once I have detected the baseline masks, now how can I convert that into textline boxes/polygons

**Comment by CrazyCrud** [comment]
_dhSegment_ does not return the bounding boxes of text lines so you need some additional computation. I tried a very basic approach by using the horizontal projection to extract the height of text lines and construct a text box (see [here](https://github.com/CrazyCrud/simple-text-line-extraction)).
A very interesting read is the paper [Influence of Text Line Segmentation](https://www.researchgate.net/publication/308812348_Influence_of_text_line_segmentation_in_Handwritten_Text_Recognition) which goes more in-depth about this topic; maybe you can get some ideas from it.
