### ISSUE TITLE
how to get the baseline or text boxes for your model?

### ISSUE THREAD

**Issue by zzdang** [dhlab-epfl/dhSegment#9]
Hello,I want to use your code to detect text boxes from scaned PDF.
But I don't know your trained model is for page extraction or  both for page extraction and baseline detection?
Thank you very much!

**Comment by solivr** [comment]
Hi,
The trained model we provide in the demo is for page extraction only. If you want to detect baselines you'll have to train your own model (you can use the READ-BAD dataset).
